version: "3.1"

language: "en"

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 50    # Reduced epochs to avoid overfitting
  constrain_similarities: true
  model_confidence: softmax

policies:
- name: MemoizationPolicy
  max_history: 5
- name: TEDPolicy
  max_history: 5
  epochs: 50    # Reduced epochs
  constrain_similarities: true
  model_confidence: softmax
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
assistant_id: 20250313-110833-instant-tee
